Added support for json input via stdin in example
benmcollins/libjwt pull request #146
Opened 2021-03-19 15:15 UTC by p-gentili

Given #145 and the TODO comment inside the example main-gen.c I think this PR may be useful for those who need to encode more complicated json.

2021-03-30 15:35 UTC, benmcollins requested changes
Change the title to show "from command line" since this is not `stdin`

Thanks for the changes.

2021-03-30 15:35 UTC, benmcollins commented on examples/main-gen.c
> +			strcpy(opt_json, optarg);
Let's use `strdup()` instead, and please check for NULL.

2021-03-30 15:35 UTC, benmcollins commented on examples/main-gen.c
> +	strcpy(opt_json, "{}");
Set this to `opt_json = NULL` so we only create this when it's passed on the command line.

2021-03-30 15:35 UTC, benmcollins commented on examples/main-gen.c
> +	ret = jwt_add_grants_json(jwt, opt_json);
if (opt_json != NULL) {
        ret = jwt_add_grants_json(jwt, opt_json);
        /* Add check for error in ret */
    }

2021-03-30 15:35 UTC, benmcollins commented on examples/main-gen.c
> +	free(opt_json);
if (opt_json != NULL)
        free(opt_json);

2021-04-03 08:57 UTC, p-gentili commented
Just updated with your suggestions. Thanks.

2021-04-03 13:05 UTC, merged